openapi: 3.0.1
info:
  title: STD21101 API
  description: 'Global description of my API'
  version: 1.0.0
servers:
 - url: https://STD2110.com
tags: 
 - name: Salle_A
   
 - name: Salle_B
paths:
 /Salle_A:
    post:
      tags:
        - Salle_A
      operationId: PostProjection
      summary: Create new Projection
      description: Create new Projection
      responses:
        200: 
          description: Projection to be created
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/CreateProjection'
        400:
          description: Bad request
    get: 
      tags:
        - Salle_A
      operationId: GetFilm
      summary : Get all Film
      description: Get all Film with details
      responses:
        200:
          description: Details of the Film
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        400:
          description: Bad request  
    put:
      tags:
        - Salle_A 
      operationId: putProjection
      summary: Update an existing Projection
      description: Change all information of Projection
      requestBody:
        description: Projection to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjection'
        required: true
      responses:
        200:
          description: Successful Updating 
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/CreateProjection'
                
        400:
          description: Bad request 
    patch:
      tags:
        - Salle_A
      operationId: patchProjection
      summary: Update an existing Projection
      description: Change some information of Projection
      requestBody:
        description: Projection to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjection'
        required: true
      responses:
        200:
          description: Successful Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProjection'
        400:
          description: Bad request
    delete:
      tags: 
        - Salle_A
      operationId: deleteFilm
      summary: Delete Film
      description: Delete Film
      responses:
        200:
          description: Successful Delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        400:
          description: Bad request          
 /Salle_B:
    post:
      tags:
        - Salle_B
      summary: Create new Projection
      description: Create new Projection
      responses:
        200: 
          description: Projection to be created
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/CreateProjection'
        400:
          description: Bad request
    get:
      tags:
        - Salle_B
      operationId: getFilm
      summary: get all Film
      description: get all Film with details
      responses:
        200: 
          description: Details of the Film
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        400:
          description: Bad request
    put:
      tags:
        - Salle_B
      summary: Update an existing Projection
      description: Change all information of Projection
      requestBody:
        description: Projection to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjection'
        required: true
      responses:
        200:
          description: Successful Updating 
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/CreateProjection'
                
        400:
          description: Bad request  
    patch:
      tags:
        - Salle_B
      summary: Update an existing Projection
      description: Change some information of Projection
      requestBody:
        description: Projection to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjection'
        required: true
      responses:
        200:
          description: Successful Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProjection'
        400:
          description: Bad request          
    delete:
      tags: 
        - Salle_B
      summary: Delete Film
      description: Delete Film
      responses:
        200:
          description: Successful Delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        400:
          description: Bad request  

components:
  schemas:
    Film:
      type: object
      properties:
        titre:
          type: string
          example: "50ShadesOfBlack"
        date:
          type: string
          format: date
          example: "2022-01-01"
        résumé:
          type: string
          example: "il etait une fois..."
        réalisateur:
          type: string
          example: "Johnny Deep"
        durée:
          type: string
          format: time
          example: "2h 30mn"
    Salle_A:
      type: object
      properties: 
        numéro:
          type: integer
          example: 10
        capacité_d'acceuil:
          type: integer
          example: 400
    Salle_B:
      type: object
      properties: 
        numéro:
          type: integer
          example: 10
        capacité_d'acceuil:
          type: integer
          example: 300
    CreateProjection:
      allOf:
        - $ref: '#/components/schemas/Film'
        - $ref: '#/components/schemas/Salle_A'
        - $ref: '#/components/schemas/Salle_B'
      type: object
      properties:
        diffusion:
          type: string
          format: time
          example: "14h 30min"